//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EppsoftRecolector.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adjunto
    {
        public int IdAdjunto { get; set; }
        public int IdRegistroActividad { get; set; }
        public string UrlAdjunto { get; set; }
        public string TipoAdjunto { get; set; }
    
        public virtual RegistroActividad RegistroActividad { get; set; }
    }
}
