//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EppsoftRecolector.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Caso
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Caso()
        {
            this.RegistroActividad = new HashSet<RegistroActividad>();
        }
    
        public int IdCaso { get; set; }
        public int IdProceso { get; set; }
        public int IdCliente { get; set; }
        public string NoDeCaso { get; set; }
        public string NombreRadicador { get; set; }
        public string NumeroDeTramite { get; set; }
        public System.DateTime FechaInicioProceso { get; set; }
        public Nullable<System.DateTime> FechaOferta { get; set; }
        public string DestinacionPrestamo { get; set; }
        public string CiudadOficinaUtilizacion { get; set; }
        public int IdCiudadUtilizacion { get; set; }
        public string MontoAprobado { get; set; }
        public string PesosUVR { get; set; }
        public string PresentaSubsidio { get; set; }
        public string FolioMatricula { get; set; }
        public string ObsercaionAprobarCreditoEInformar { get; set; }
    
        public virtual Ciudad Ciudad { get; set; }
        public virtual Cliente Cliente { get; set; }
        public virtual Proceso Proceso { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RegistroActividad> RegistroActividad { get; set; }
    }
}
