//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EppsoftRecolector.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Planilla
    {
        public int idPlanilla { get; set; }
        public int iCodigoPlanilla { get; set; }
        public int idGenerador { get; set; }
        public System.DateTime dFechaRecolección { get; set; }
        public int idVehiculoRecoleccion { get; set; }
        public int iReportadoUsuarioKg { get; set; }
        public int iRecolectadoKg { get; set; }
        public string sRecipientes { get; set; }
        public Nullable<bool> bEncontrados { get; set; }
        public Nullable<bool> bRecogidos { get; set; }
        public string sNombreUsuarioEntrega { get; set; }
        public byte[] imgFirmaRecolector { get; set; }
        public byte[] imgFirmaUsuario { get; set; }
        public int idNovedadesServicio { get; set; }
        public string sOtrasNovedades { get; set; }
        public int idClaseProducto { get; set; }
    
        public virtual ClaseProducto ClaseProducto { get; set; }
        public virtual NovedadServicio NovedadServicio { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual Vehiculo Vehiculo { get; set; }
    }
}
