//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Categoria
    {
        public int IdCategoria { get; set; }
        public string Nombre { get; set; }
        public string Color { get; set; }
        public int ValorMinimo { get; set; }
        public int ValorMaximo { get; set; }
        public bool Activo { get; set; }
    }
}
