//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegistroActividad
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RegistroActividad()
        {
            this.Adjunto = new HashSet<Adjunto>();
        }
    
        public int IdRegistroActividad { get; set; }
        public int IdActividad { get; set; }
        public int IdCaso { get; set; }
        public string EstadoActividad { get; set; }
        public Nullable<System.DateTime> FechaVencimientoActividad { get; set; }
        public string usuarioResponsable { get; set; }
        public Nullable<System.DateTime> FechaCreacionActividad { get; set; }
        public Nullable<System.DateTime> FechaInicioActividad { get; set; }
        public Nullable<System.DateTime> FechaFinalizacionActividad { get; set; }
        public Nullable<long> TiempoDeEjecucion { get; set; }
        public Nullable<long> TiempoDeEspera { get; set; }
        public Nullable<long> DuracionTotal { get; set; }
        public Nullable<bool> HitoFinalizado { get; set; }
    
        public virtual Actividad Actividad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Adjunto> Adjunto { get; set; }
        public virtual Caso Caso { get; set; }
    }
}
